version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5003/api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=sqlite:./cryptotracker.db
      - JWT_SECRET=my_jwt_secret_key_change_this_in_production
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cryptotracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cryptotracker-network

volumes:
  postgres_data:

networks:
  cryptotracker-network:
    driver: bridge