version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - cryptotracker-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_URL=http://localhost:3000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=cryptotracker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - database
    networks:
      - cryptotracker-network

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cryptotracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cryptotracker-network

volumes:
  postgres_data:

networks:
  cryptotracker-network:
    driver: bridge